"""Text-to-speech synthesis via OpenRouter — turns a written episode into an mp3.

Part of the podcast channel, the second recorded phase-gate exception
(DESIGN §13.3). The one module that touches OpenRouter's `/api/v1/audio/speech`
endpoint. Takes the ordered dialogue turns `report.podcast.parse_script` already
recovered from the vault file — never the `BuiltScript` a fresh Opus call
produced — so the audio can never disagree with what a human reading the vault
sees (DESIGN §13.2's same-context contract, the same reasoning `report/podcast.py`'s
own docstring gives for its round trip).

### Why per-line, not one multi-speaker request

OpenRouter's TTS endpoint is one voice per request (confirmed against the
provider's own docs, 2026-08-07) — there is no single-request multi-speaker
passthrough to fall back to even if a future Gemini variant claims one, so
this module's only synthesis path is: coalesce consecutive same-speaker turns
into as few chunks as the dialogue allows, synthesize each chunk with its
speaker's configured voice, and `ffmpeg -f concat` the results in order. A
single-request multi-speaker call (were one ever verified to exist) would be
a pure optimization on top of this, not a replacement for it — nothing here
assumes it will arrive.

### Pricing is not one number

OpenRouter's TTS catalog spans two genuinely different billing shapes: most
models price per input character, but at least one (Gemini's TTS line) prices
per *token*, input and output both — and output tokens track *synthesized
audio length*, which this module cannot know without already having paid for
it. `tts_spend_usd` therefore only prices models confirmed to bill per
character; an unrecognized `model` (which includes every token-priced model,
deliberately) falls back to `_UNKNOWN_MODEL_FALLBACK_USD_PER_MILLION_CHARS` —
set at the most expensive *known* per-character rate, not a guess at zero, so
an operator who points `tts_model` at an unpriced or token-billed model sees
an expensive number in `signalforge status` rather than a falsely cheap one
(CLAUDE.md §7 — a wrong number that hides spend is worse than one that
overstates it). This is also why the real budget alarm,
`TTS_MONTHLY_CEILING_USD`, is priced in dollars from the worst *known*
per-character rate rather than in characters: a character-only ceiling
generous enough for the cheapest model would already be tens of dollars a
month on the most expensive one, and could sit under a character cap while
the real bill blew past it — an `llm-cost-guard` review caught exactly this
gap in an earlier draft of this module. `TTS_MONTHLY_CHARACTER_CEILING`
still exists alongside it, as a narrower, model-agnostic volume check.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import tempfile
import time
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final

import httpx
from pydantic import SecretStr
from tenacity import RetryCallState, Retrying, retry_if_exception_type, stop_after_attempt
from tenacity.wait import wait_exponential

from signalforge.config import PodcastChannelConfig
from signalforge.ingest.base import DEFAULT_USER_AGENT, parse_retry_after
from signalforge.report.podcast import ScriptTurn

__all__ = [
    "TTS_MAX_CHARS",
    "TTS_MONTHLY_CEILING_USD",
    "TTS_MONTHLY_CHARACTER_CEILING",
    "SynthesisError",
    "SynthesisResult",
    "synthesize_episode",
    "tts_spend_usd",
]

logger = logging.getLogger(__name__)

_TTS_ENDPOINT: Final = "https://openrouter.ai/api/v1/audio/speech"

TTS_MAX_CHARS: Final = 14_000
"""Hard refusal ceiling on total dialogue characters sent to the provider —
double defense with `synth.podcast.PODCAST_MAX_SCRIPT_CHARS` (the same limit,
enforced a second time here in case a vault file was ever hand-edited or
regenerated by a future caller that skips that check). OpenRouter's own
per-request limit is higher (15,000 per the plan's cost model), so this bound
is this pipeline's, not the provider's."""

_PRICE_PER_MILLION_CHARS_USD: Final[dict[str, float]] = {
    # Sourced from OpenRouter's models catalog, checked 2026-08-07. Every
    # entry here bills per input character — see this module's docstring for
    # why a token-priced model (Gemini's TTS line, notably) is deliberately
    # absent rather than approximated. Re-verify before trusting this table
    # for a model added to `settings.yaml` months from now; TTS pricing on
    # OpenRouter has already changed shape at least once (Gemini moved from
    # a flat per-character quote to per-token between preview revisions).
    "hexgrad/kokoro-82m": 0.62,
    "qwen/qwen-audio-3.0-tts-flash": 15.00,
    "microsoft/mai-voice-2-flash": 15.00,
    "x-ai/grok-voice-tts-1.0": 15.00,
    "microsoft/mai-voice-2": 22.00,
    "minimax/speech-2.8-turbo": 60.00,
    "minimax/speech-2.8-hd": 100.00,
    "fish-audio/s2.1-pro-free:free": 0.00,
}

_UNKNOWN_MODEL_FALLBACK_USD_PER_MILLION_CHARS: Final = max(_PRICE_PER_MILLION_CHARS_USD.values())
"""The most expensive *known* per-character rate in the table above,
computed rather than copied as a separate literal — a hand-copied number
here would silently understate the fallback the moment a pricier model is
added to the table above without this constant being updated to match (an
`llm-cost-guard` review caught exactly this shape of drift risk). Used for
any model this module cannot price, including every token-priced model. See
this module's docstring: an unrecognized model must read as expensive in
`signalforge status`, never as free."""

TTS_MONTHLY_CHARACTER_CEILING: Final = 500_000
"""A model-agnostic sanity bound on total monthly TTS volume — catches a
genuine runaway (e.g. a retention bug re-synthesizing already-published
episodes) regardless of which model is configured. This is **not** the
budget alarm; see `TTS_MONTHLY_CEILING_USD` for that. A character count
alone cannot answer "is this over budget," since $/char spans a 160x range
across this module's own price table (`$0.62` to `$100.00` per million) —
a character ceiling generous enough to survive a legitimate backfill on the
cheapest model is already ~$50/month on the most expensive one.

Worked worst case: one script at the hard cap (`TTS_MAX_CHARS` = 14,000
chars) every day for 31 days is 434,000 chars/month. 500,000 leaves headroom
for a backfill or a `--force-script` re-run without immediately tripping the
alarm on a single busy day.
"""

TTS_MONTHLY_CEILING_USD: Final = (
    TTS_MAX_CHARS * 31 * _UNKNOWN_MODEL_FALLBACK_USD_PER_MILLION_CHARS / 1_000_000
)
"""The actual budget alarm (DESIGN §8) — priced in dollars, like its
siblings `llm.PODCAST_MONTHLY_CEILING_USD` / `llm.SCOUT_MONTHLY_CEILING_USD`,
so it can fail for a cost reason rather than merely a volume one. Computed
directly from `TTS_MAX_CHARS` and the worst *known* per-character price
(`_UNKNOWN_MODEL_FALLBACK_USD_PER_MILLION_CHARS`) rather than hand-typed, so
it cannot go stale independently of the table it is priced from — the same
"computed, not copied" fix applied to the fallback constant above.

Worked worst case: 14,000 chars × 31 days × $100.00/M chars ≈ **$43.40/month**
— already past the whole-pipeline $30 alarm on its own, and stacked with
`PODCAST_MONTHLY_CEILING_USD` ($23) and `SCOUT_MONTHLY_CEILING_USD` ($13) is
a combined worst case near $80/month. That is the same honest disclosure
those two ceilings already make about summing past $30 on paper (see
`PODCAST_MONTHLY_CEILING_USD`'s docstring) — not a contradiction to paper
over. It reflects the *most expensive currently-known* model at the *hard
per-episode cap* every single day; the shipped default (`hexgrad/kokoro-82m`)
prices the same worst case at **~$0.27/month**, over two orders of magnitude
lower. Neither ceiling family is enforced at runtime; both are numbers
`signalforge status` (Stage 6) compares actual month-to-date spend against,
so an operator notices before the bill does (CLAUDE.md §7) — the whole
point of this constant is to be the one Stage 6 actually reads for that
comparison, not `TTS_MONTHLY_CHARACTER_CEILING`.
"""

_MAX_ATTEMPTS: Final = 3
"""Same reasoning as `deliver.email._MAX_ATTEMPTS`: a cron job, not a
user waiting on a response, so a failed chunk is retried tomorrow's run
rather than hammered."""

_TIMEOUT_SECONDS: Final = 60.0
"""Longer than email's 15s — synthesizing a chunk of spoken dialogue takes
real provider-side time, and a timeout here should mean "slow", not "gone"."""

_MAX_RETRY_AFTER_SECONDS: Final = 60.0

_RETRYABLE_STATUS: Final[frozenset[int]] = frozenset({408, 429, 500, 502, 503, 504})
"""Deliberately local, not shared with `deliver.email` or `ingest.base` — see
`deliver.email._RETRYABLE_STATUS`'s docstring for why a policy set is not
worth sharing even when the values happen to match today."""

_REPLAYABLE_TRANSPORT_ERRORS: Final = (
    httpx.ConnectError,
    httpx.ConnectTimeout,
    httpx.PoolTimeout,
)
"""Connect-phase-only, same as `deliver.email`. A TTS request is paid; a
`ReadTimeout` means the request was fully sent and audio may already have
been generated, so replaying it risks double-billing a chunk that already
succeeded server-side."""


def tts_spend_usd(chars: int, model: str) -> float:
    """What synthesizing `chars` characters on `model` costs, in dollars.

    See this module's docstring for the fallback behavior on a model this
    table cannot price. `chars` should be the count actually sent to the
    provider (post-coalescing, since coalescing does not change the total
    character count, only the number of requests it takes to send them).
    """
    price = _PRICE_PER_MILLION_CHARS_USD.get(model)
    if price is None:
        logger.warning(
            "tts model has no known per-character price; using the worst-case fallback",
            extra={"model": model},
        )
        price = _UNKNOWN_MODEL_FALLBACK_USD_PER_MILLION_CHARS
    return chars * price / 1_000_000


class SynthesisError(Exception):
    """Synthesis could not produce audio — a refusal, a provider failure
    after retries, or a missing `ffmpeg`. Raised rather than returned so the
    caller cannot mistake a failed episode for a silent one (mirrors
    `deliver.email.SendError`).

    `characters_sent` carries whatever was already billed before this
    failure — 0 for every pre-flight refusal (no ffmpeg, over-length,
    empty episode), but nonzero when chunk *N* of an episode fails after
    chunks 1..N-1 already succeeded, or when the post-synthesis `ffmpeg`
    concat step fails after every chunk succeeded. NEVER rule 11's
    discipline (never silently drop a real spend), applied to TTS
    characters instead of LLM tokens — `deliver_podcast` reads this on the
    failure path so a partial-episode failure still lands in
    `runs.tts_characters`.
    """

    def __init__(self, message: str, *, characters_sent: int = 0) -> None:
        super().__init__(message)
        self.characters_sent = characters_sent


class _RetryableStatus(Exception):
    """Internal: a status worth retrying, carrying any `Retry-After` hint."""

    def __init__(self, status_code: int, retry_after: float | None) -> None:
        super().__init__(f"provider returned HTTP {status_code}")
        self.status_code = status_code
        self.retry_after = retry_after


@dataclass(frozen=True, slots=True)
class SynthesisResult:
    """One episode's synthesized audio, and what it cost to make."""

    audio: bytes
    characters: int
    """Total characters actually sent to the provider — the number
    `tts_spend_usd` and `runs.tts_characters` should both be given."""


@dataclass(frozen=True, slots=True)
class _Chunk:
    voice: str
    text: str


def _coalesce(
    turns: Sequence[ScriptTurn], *, presenter_a: str, presenter_b: str, voice_a: str, voice_b: str
) -> list[_Chunk]:
    """Merge consecutive same-speaker turns into as few chunks as the
    dialogue allows — fewer, longer synthesis requests for the same total
    character count, which is what "coalesce" buys here: cost is unchanged,
    request count (and therefore latency and retry surface) drops.

    Raises `SynthesisError` for a turn whose speaker matches neither
    configured presenter — a data problem (a stale vault file synthesized
    against a config whose presenter names have since changed), not a case
    to guess a voice for.
    """
    chunks: list[_Chunk] = []
    for turn in turns:
        if turn.speaker == presenter_a:
            voice = voice_a
        elif turn.speaker == presenter_b:
            voice = voice_b
        else:
            raise SynthesisError(
                f"turn speaker {turn.speaker!r} matches neither configured presenter "
                f"({presenter_a!r}, {presenter_b!r}); vault file and config have drifted"
            )
        if chunks and chunks[-1].voice == voice:
            chunks[-1] = _Chunk(voice=voice, text=f"{chunks[-1].text} {turn.text}")
        else:
            chunks.append(_Chunk(voice=voice, text=turn.text))
    return chunks


def _wait_honoring_retry_after(state: RetryCallState) -> float:
    """Exponential backoff, floored by the provider's `Retry-After` — same
    rule as `deliver.email._wait_honoring_retry_after`."""
    base: float = wait_exponential(multiplier=1, min=1, max=10)(state)
    exc = state.outcome.exception() if state.outcome is not None else None
    if isinstance(exc, _RetryableStatus) and exc.retry_after is not None:
        return max(base, min(exc.retry_after, _MAX_RETRY_AFTER_SECONDS))
    return base


def _synthesize_chunk_once(
    client: httpx.Client, *, chunk: _Chunk, model: str, api_key: SecretStr
) -> bytes:
    """One POST, one chunk. Returns raw mp3 bytes."""
    response = client.post(
        _TTS_ENDPOINT,
        json={
            "model": model,
            "input": chunk.text,
            "voice": chunk.voice,
            "response_format": "mp3",
        },
        headers={
            "Authorization": f"Bearer {api_key.get_secret_value()}",
            "User-Agent": DEFAULT_USER_AGENT,
        },
    )
    if response.status_code in _RETRYABLE_STATUS:
        raise _RetryableStatus(
            response.status_code, parse_retry_after(response.headers.get("retry-after"))
        )
    if not 200 <= response.status_code < 300:
        raise SynthesisError(
            f"tts provider returned HTTP {response.status_code}: {response.text[:300]}"
        )
    return response.content


def _synthesize_chunk(
    client: httpx.Client,
    *,
    chunk: _Chunk,
    model: str,
    api_key: SecretStr,
    sleep: Callable[[int | float], None],
) -> bytes:
    try:
        for attempt in Retrying(
            stop=stop_after_attempt(_MAX_ATTEMPTS),
            wait=_wait_honoring_retry_after,
            retry=retry_if_exception_type((_RetryableStatus, *_REPLAYABLE_TRANSPORT_ERRORS)),
            sleep=sleep,
            reraise=True,
        ):
            with attempt:
                return _synthesize_chunk_once(client, chunk=chunk, model=model, api_key=api_key)
    except (_RetryableStatus, httpx.TransportError) as exc:
        replayed = isinstance(exc, (_RetryableStatus, *_REPLAYABLE_TRANSPORT_ERRORS))
        detail = f"after {_MAX_ATTEMPTS} attempts" if replayed else "without retrying"
        raise SynthesisError(f"tts chunk synthesis failed {detail}: {exc}") from exc
    raise SynthesisError("tts chunk synthesis produced no result")  # pragma: no cover


def _concat_mp3(chunks: Sequence[bytes]) -> bytes:
    """`ffmpeg -f concat` the chunk mp3s in order into one episode file.

    Stream-copied (`-c copy`), not re-encoded: every chunk came from the same
    provider and `response_format`, so the codec is already consistent and
    re-encoding would spend CPU for no quality gain. Raises `SynthesisError`
    on any ffmpeg failure rather than a bare `CalledProcessError`, matching
    every other failure mode this module reports.
    """
    if len(chunks) == 1:
        # Nothing to concatenate — running ffmpeg on a single-file list
        # would be a correct no-op, but skipping it entirely means an
        # episode with one speaker throughout never depends on ffmpeg at
        # all, and there is nothing to test that ffmpeg does not already
        # cover for the multi-chunk case.
        return chunks[0]

    with tempfile.TemporaryDirectory(prefix="signalforge-tts-") as tmpdir:
        tmp = Path(tmpdir)
        list_path = tmp / "concat.txt"
        lines = []
        for index, chunk in enumerate(chunks):
            chunk_path = tmp / f"chunk-{index:04d}.mp3"
            chunk_path.write_bytes(chunk)
            lines.append(f"file '{chunk_path.name}'")
        list_path.write_text("\n".join(lines), encoding="utf-8")

        output_path = tmp / "episode.mp3"
        try:
            subprocess.run(
                [
                    "ffmpeg",
                    "-y",
                    "-f",
                    "concat",
                    "-safe",
                    "0",
                    "-i",
                    str(list_path),
                    "-c",
                    "copy",
                    str(output_path),
                ],
                cwd=tmp,
                capture_output=True,
                check=True,
                timeout=120,
            )
        except subprocess.CalledProcessError as exc:
            raise SynthesisError(
                f"ffmpeg concat failed (exit {exc.returncode}): {exc.stderr[-500:]!r}"
            ) from exc
        except subprocess.TimeoutExpired as exc:
            raise SynthesisError("ffmpeg concat timed out") from exc
        return output_path.read_bytes()


def synthesize_episode(
    turns: Sequence[ScriptTurn],
    *,
    config: PodcastChannelConfig,
    api_key: SecretStr,
    sleep: Callable[[int | float], None] = time.sleep,
) -> SynthesisResult:
    """Synthesize one episode's full dialogue into a single mp3.

    Raises `SynthesisError` for every failure mode: no `ffmpeg` on `PATH`, an
    over-length script (`TTS_MAX_CHARS`), a speaker/config mismatch, or a
    provider failure after retries. None of these should fail the whole run
    (CLAUDE.md §7) — the caller (`deliver/podcast.py`) turns this into a
    `DeliveryOutcome`, the same posture `deliver.email.SendError` gets.

    `ffmpeg` is checked *before* any request is sent, not at the concat
    step: paying for synthesis only to discover the concat step cannot run
    would spend real money for a config problem (CLAUDE.md §10 rule 6).
    """
    if shutil.which("ffmpeg") is None:
        raise SynthesisError(
            "ffmpeg is not on PATH; install it before enabling the podcast channel "
            "(config-shaped error, not a provider failure)"
        )

    chunks = _coalesce(
        turns,
        presenter_a=config.presenter_a,
        presenter_b=config.presenter_b,
        voice_a=config.voice_a,
        voice_b=config.voice_b,
    )
    # Checked against the *coalesced* total, not the pre-coalescing sum over
    # `turns`: `_coalesce` joins merged turns with a space, so the coalesced
    # total is what is actually billed — a code-reviewer pass caught the
    # pre-coalescing figure quietly under-enforcing this cap and
    # under-reporting spend by one character per merge.
    total_chars = sum(len(chunk.text) for chunk in chunks)
    if total_chars > TTS_MAX_CHARS:
        raise SynthesisError(
            f"episode is {total_chars} characters, over the {TTS_MAX_CHARS} tts hard cap "
            "(this should already be unreachable via synth.podcast's own cap; refusing anyway)"
        )
    if total_chars == 0:
        raise SynthesisError("episode has no dialogue to synthesize")

    audio_chunks: list[bytes] = []
    characters_sent = 0
    with httpx.Client(timeout=_TIMEOUT_SECONDS) as client:
        for chunk in chunks:
            try:
                audio = _synthesize_chunk(
                    client, chunk=chunk, model=config.tts_model, api_key=api_key, sleep=sleep
                )
            except SynthesisError as exc:
                # `characters_sent` here is only ever the chunks that
                # already succeeded before this one — the failed chunk's
                # own retries never produced a billable response, so it
                # contributes nothing (see `SynthesisError`'s docstring).
                raise SynthesisError(str(exc), characters_sent=characters_sent) from exc
            audio_chunks.append(audio)
            characters_sent += len(chunk.text)

    logger.info(
        "synthesized podcast episode",
        extra={"chunks": len(chunks), "characters": characters_sent, "model": config.tts_model},
    )
    try:
        audio = _concat_mp3(audio_chunks)
    except SynthesisError as exc:
        # Every chunk was already billed by this point — a concat failure
        # must not lose that spend either.
        raise SynthesisError(str(exc), characters_sent=characters_sent) from exc
    return SynthesisResult(audio=audio, characters=characters_sent)
